// agile-agents — auto-generated by the daemon (T022, packages/daemon/src/pi/install.ts). Do not edit; edits are overwritten on the next Pi session spawn.
/**
 * The `agile` Pi extension (spike-findings.md §C4). `install.ts` copies
 * this file's source verbatim to `~/.pi/agent/extensions/agile.ts`, so it
 * loads for every local `pi` session; `GATE_ENV_VAR` keeps it a no-op for a
 * human's own sessions.
 *
 * Self-contained: installed, it runs inside `pi`'s process and may import
 * nothing but Node builtins. Pi's types are mirrored locally (checked
 * against `@earendil-works/pi-coding-agent@0.85.1`'s
 * `dist/core/extensions/types.d.ts`).
 *
 * `tool_call` forwards to the same `hook.pre_tool_use` RPC as Claude's
 * PreToolUse hook and translates the reply into Pi's `{block, reason}`.
 * The heartbeat rides on that call, plus a timer for tool-call-free turns.
 *
 * `tool_result` rewriting is the one thing Claude's hook cannot do and
 * Pi's API can: large test output is distilled locally, alongside a
 * `hook.post_tool_use` call for the usage record.
 *
 * Urgent messages arrive as a denied call's reason, as for Claude. Pi's
 * `tool_call` result has no `additionalContext`, so normal-priority inbox
 * messages are delivered via `before_agent_start`'s `message`, once per
 * turn.
 */

import { connect } from 'node:net';

// ---------------------------------------------------------------------------
// Config, read at load from the env vars the daemon sets on a Pi session.
// ---------------------------------------------------------------------------

/** `'1'` on every Pi session the daemon spawns; otherwise the extension registers nothing. */
export const GATE_ENV_VAR = 'AGILE_PI_GATE';

export interface AgileExtensionEnv {
  AGILE_PI_GATE?: string;
  AGILE_SOCKET_PATH?: string;
  AGILE_AGENT?: string;
  AGILE_TICKET?: string;
}

/** Heartbeat cadence (30 s). */
export const HEARTBEAT_INTERVAL_MS = 30_000;

/** Above this many characters a test-run-shaped `bash` result is distilled (signal over volume). */
export const TEST_OUTPUT_REWRITE_THRESHOLD = 2000;

/** Trailing lines of a distilled run kept verbatim (the failure tail is usually what's needed). */
const TEST_OUTPUT_TAIL_LINES = 40;

// ---------------------------------------------------------------------------
// Local typings for the slice of the Pi extension API used here.
// ---------------------------------------------------------------------------

export interface PiToolCallEvent {
  type: 'tool_call';
  toolCallId: string;
  toolName: string;
  input: Record<string, unknown>;
}

export interface PiToolCallResult {
  block?: boolean;
  reason?: string;
}

export interface PiTextContent {
  type: 'text';
  text: string;
}

export interface PiToolResultEvent {
  type: 'tool_result';
  toolCallId: string;
  toolName: string;
  input: Record<string, unknown>;
  content: PiTextContent[];
  isError: boolean;
}

export interface PiToolResultEventResult {
  content?: PiTextContent[];
  /**
   * Echoes the original `event.isError` on every rewrite. Whether Pi merges
   * a partial result onto the event or replaces it can't be checked from
   * this repo (Pi is not a workspace dependency), and setting it explicitly
   * is correct either way.
   */
  isError?: boolean;
}

export interface PiBeforeAgentStartEvent {
  type: 'before_agent_start';
  prompt: string;
}

export interface PiBeforeAgentStartResult {
  message?: {
    customType: string;
    content: PiTextContent[];
    display?: string;
  };
}

export interface PiExtensionContext {
  cwd: string;
}

export type PiHandler<E, R> = (
  event: E,
  ctx: PiExtensionContext,
) => Promise<R | undefined> | R | undefined;

export interface PiExtensionApi {
  on(event: 'tool_call', handler: PiHandler<PiToolCallEvent, PiToolCallResult>): void;
  on(event: 'tool_result', handler: PiHandler<PiToolResultEvent, PiToolResultEventResult>): void;
  on(
    event: 'before_agent_start',
    handler: PiHandler<PiBeforeAgentStartEvent, PiBeforeAgentStartResult>,
  ): void;
  on(event: 'agent_settled', handler: PiHandler<{ type: 'agent_settled' }, void>): void;
  on(event: 'session_shutdown', handler: PiHandler<{ type: 'session_shutdown' }, void>): void;
}

// ---------------------------------------------------------------------------
// A minimal unix-socket JSON-RPC 2.0 client, the same wire format as the
// CLI's `callRpc` (this file can't import it). A divergence between the
// two is a bug.
// ---------------------------------------------------------------------------

export interface RpcClient {
  call<T = unknown>(method: string, params?: unknown): Promise<T>;
}

let rpcId = 1;

export function createSocketRpcClient(socketPath: string, timeoutMs = 5000): RpcClient {
  return {
    call<T>(method: string, params?: unknown): Promise<T> {
      return new Promise<T>((resolve, reject) => {
        const id = rpcId++;
        const socket = connect(socketPath);
        let buffer = '';
        let settled = false;

        const finish = (fn: () => void) => {
          if (settled) return;
          settled = true;
          clearTimeout(timer);
          socket.destroy();
          fn();
        };

        const timer = setTimeout(() => {
          finish(() => reject(new Error(`agile pi extension: timed out calling ${method}`)));
        }, timeoutMs);

        socket.on('error', (err: Error) => {
          finish(() => reject(new Error(`agile pi extension: ${method}: ${err.message}`)));
        });
        socket.on('close', () => {
          finish(() =>
            reject(
              new Error(
                `agile pi extension: daemon closed connection before replying to ${method}`,
              ),
            ),
          );
        });
        socket.on('connect', () => {
          socket.write(`${JSON.stringify({ jsonrpc: '2.0', id, method, params })}\n`);
        });
        socket.setEncoding('utf8');
        socket.on('data', (chunk: string) => {
          buffer += chunk;
          let nl = buffer.indexOf('\n');
          while (nl !== -1) {
            const line = buffer.slice(0, nl).trim();
            buffer = buffer.slice(nl + 1);
            nl = buffer.indexOf('\n');
            if (!line) continue;
            let parsed: { id?: unknown; result?: unknown; error?: { message?: string } };
            try {
              parsed = JSON.parse(line);
            } catch {
              continue;
            }
            if (parsed.id !== id) continue;
            finish(() => {
              if (parsed.error) {
                reject(new Error(`agile pi extension: ${method}: ${parsed.error?.message}`));
              } else {
                resolve(parsed.result as T);
              }
            });
            return;
          }
        });
      });
    },
  };
}

// ---------------------------------------------------------------------------
// Pure logic, unit-testable with no socket or process.
// ---------------------------------------------------------------------------

/** The fields of `hook.pre_tool_use`'s Claude-shaped reply this file reads. */
export interface HookPreToolUseReply {
  hookSpecificOutput?: {
    permissionDecision?: 'allow' | 'deny' | 'ask';
    permissionDecisionReason?: string;
  };
}

/**
 * The daemon's verdict as Pi's `tool_call` result. `ask` has no channel
 * back to the daemon's gates from a Pi handler (`ui.confirm` asks only the
 * local user), so it fails safe as a deny with the same reason.
 */
export function toPiToolCallResult(reply: HookPreToolUseReply): PiToolCallResult {
  const out = reply.hookSpecificOutput;
  if (!out || out.permissionDecision === 'allow' || out.permissionDecision === undefined) {
    return {};
  }
  return { block: true, reason: out.permissionDecisionReason ?? 'AGILE-GATE: blocked' };
}

/** Commands that look like a test run: the only results rewritten. */
const TEST_COMMAND_PATTERN =
  /\b(npm|pnpm|yarn|bun|go|cargo|pytest|jest|vitest|mocha|rspec|gradle|mvn)\b.*\btest\b|\bpytest\b|\bjest\b|\bvitest\b|\bgo test\b/i;

export function looksLikeTestRun(toolName: string, input: Record<string, unknown>): boolean {
  const command = input.command;
  return toolName === 'bash' && typeof command === 'string' && TEST_COMMAND_PATTERN.test(command);
}

export interface SummarizedOutput {
  text: string;
  rewritten: boolean;
}

/** Failure lines kept even when a long trailing summary would push them out of the tail; bounded so the summary stays small. */
const MAX_FAIL_LINES = 60;

/**
 * Distills large test output: counts, the failure lines (bounded, deduped
 * against the tail) and a verbatim tail. Below
 * `TEST_OUTPUT_REWRITE_THRESHOLD` the text passes through unchanged.
 */
export function summarizeTestOutput(text: string): SummarizedOutput {
  if (text.length <= TEST_OUTPUT_REWRITE_THRESHOLD) return { text, rewritten: false };

  const lines = text.split('\n');
  const FAIL_PATTERN = /fail|error|✗|✕|AssertionError/i;
  const PASS_PATTERN = /pass|✓|✔|\bok\b/i;
  let failing = 0;
  let passing = 0;
  const failLines: string[] = [];
  for (const line of lines) {
    if (FAIL_PATTERN.test(line)) {
      failing++;
      if (failLines.length < MAX_FAIL_LINES) failLines.push(line);
    } else if (PASS_PATTERN.test(line)) {
      passing++;
    }
  }
  const tail = lines.slice(-TEST_OUTPUT_TAIL_LINES);
  const tailSet = new Set(tail);
  const failLinesNotInTail = failLines.filter((l) => !tailSet.has(l));

  const sections: string[] = [];
  if (failLinesNotInTail.length > 0) {
    sections.push(
      `failure-matching lines (first ${failLinesNotInTail.length}${failing > failLinesNotInTail.length ? `, of ${failing} total` : ''}):\n${failLinesNotInTail.join('\n')}`,
    );
  }
  sections.push(`last ${tail.length} lines:\n${tail.join('\n')}`);

  const summary =
    `AGILE-SUMMARY: test run output was ${text.length} bytes ` +
    `(~${passing} pass-looking / ${failing} fail-looking lines)\n\n${sections.join('\n\n')}`;
  return { text: summary, rewritten: true };
}

/** Concatenates normal-priority inbox bodies up to a cap (a local copy of `decide.ts`'s). */
export function formatInboxMessage(
  messages: Array<{ kind: string; from: string; body: string }>,
  maxChars = 4000,
): string {
  const lines: string[] = [];
  let total = 0;
  for (const m of messages) {
    const line = `[${m.kind} from ${m.from}] ${m.body}`;
    if (total + line.length > maxChars) break;
    lines.push(line);
    total += line.length + 1;
  }
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// The extension factory.
// ---------------------------------------------------------------------------

export interface CreateAgileExtensionOptions {
  env?: AgileExtensionEnv;
  /** Test seam. Defaults to `createSocketRpcClient(env.AGILE_SOCKET_PATH)`. */
  rpc?: RpcClient;
  heartbeatIntervalMs?: number;
}

/**
 * Builds the extension. Pi's loader calls the default export; this factory
 * exists so the wiring is testable against a fake `pi` and a real RPC
 * server.
 */
export function createAgileExtension(opts: CreateAgileExtensionOptions = {}) {
  return function agileExtension(pi: PiExtensionApi): void {
    const env = opts.env ?? (process.env as AgileExtensionEnv);
    if (env[GATE_ENV_VAR] !== '1') return; // not an agile-spawned session

    const socketPath = env.AGILE_SOCKET_PATH;
    const agent = env.AGILE_AGENT;
    const ticket = env.AGILE_TICKET;
    if (!socketPath || !agent) return; // nothing to gate against; don't crash pi's loader

    const rpc = opts.rpc ?? createSocketRpcClient(socketPath);

    const heartbeat = () => {
      void rpc.call('bus.heartbeat', { agent, patch: { ticket } }).catch(() => {
        // Best effort: a missed heartbeat surfaces via the liveness sweep.
      });
    };

    pi.on('tool_call', async (event, ctx): Promise<PiToolCallResult> => {
      try {
        const reply = await rpc.call<HookPreToolUseReply>('hook.pre_tool_use', {
          cwd: ctx.cwd,
          tool_name: event.toolName,
          tool_input: event.input,
          agile_agent: agent,
          // No `additionalContext` channel here: the daemon must not fold
          // and ack normal messages into this decision (`before_agent_start`
          // delivers them).
          no_additional_context_channel: true,
        });
        return toPiToolCallResult(reply);
      } catch {
        // Fail closed: an unreachable daemon blocks the call.
        return { block: true, reason: 'AGILE-GATE: agile daemon unreachable' };
      }
    });

    pi.on('tool_result', async (event, ctx): Promise<PiToolResultEventResult | undefined> => {
      void rpc
        .call('hook.post_tool_use', {
          cwd: ctx.cwd,
          tool_name: event.toolName,
          tool_input: event.input,
          agile_agent: agent,
        })
        .catch(() => {
          // Best effort: the tool already ran.
        });

      if (!looksLikeTestRun(event.toolName, event.input)) return;
      const combined = event.content.map((c) => c.text).join('\n');
      const { text, rewritten } = summarizeTestOutput(combined);
      if (!rewritten) return;
      // A rewritten failing run must not look like a pass.
      return { content: [{ type: 'text', text }], isError: event.isError };
    });

    pi.on('before_agent_start', async (): Promise<PiBeforeAgentStartResult | undefined> => {
      type InboxMessage = { id: string; kind: string; from: string; body: string };
      let messages: InboxMessage[];
      try {
        messages = await rpc.call<InboxMessage[]>('bus.poll', { agent, priority: 'normal' });
      } catch {
        return; // best-effort delivery
      }
      if (!Array.isArray(messages) || messages.length === 0) return;
      for (const m of messages) {
        void rpc.call('bus.ack', { agent, id: m.id }).catch(() => {});
      }
      return {
        message: {
          customType: 'agile-inbox',
          content: [{ type: 'text', text: formatInboxMessage(messages) }],
          display: 'shown',
        },
      };
    });

    pi.on('agent_settled', () => {
      heartbeat();
    });

    const heartbeatTimer = setInterval(
      heartbeat,
      opts.heartbeatIntervalMs ?? HEARTBEAT_INTERVAL_MS,
    );
    // Unref'd: pi's own event loop keeps the process alive.
    heartbeatTimer.unref?.();

    pi.on('session_shutdown', () => {
      clearInterval(heartbeatTimer);
    });

    // Once at registration, to cover the gap before the first tool call.
    heartbeat();
  };
}

/** What `pi`'s extension loader calls once installed, with ambient `process.env`. */
export default createAgileExtension();
