/**
 * Installs the `agile` Pi extension into a Pi agent directory's
 * `extensions/` and sets `quietStartup` in its `settings.json`. Called per
 * Pi spawn by `runner/session.ts`; both writes are idempotent by content.
 *
 * - An existing `extensions/agile.ts` without `EXTENSION_MARKER` wasn't
 *   installed here (a user's or Terma's own extension at the same path),
 *   so it is refused, never clobbered.
 * - A hand-written `settings.json` is often JSONC; an unparseable or
 *   unwritable one is left untouched and reported via `settingsError`.
 *   `quietStartup` is cosmetic and must never block the spawn.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

/** The env var `pi` and `pi-acp` both honor for the agent dir. */
export const PI_AGENT_DIR_ENV_VAR = 'PI_CODING_AGENT_DIR';

export interface ResolvePiAgentDirOptions {
  env?: Record<string, string | undefined>;
  homeDir?: string;
}

/** Resolves the Pi agent dir the way `pi`/`pi-acp` do (`$PI_CODING_AGENT_DIR` or `~/.pi/agent`). */
export function resolvePiAgentDir(opts: ResolvePiAgentDirOptions = {}): string {
  const env = opts.env ?? process.env;
  const envDir = env[PI_AGENT_DIR_ENV_VAR];
  if (envDir) return envDir;
  return join(opts.homeDir ?? homedir(), '.pi', 'agent');
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** On `agile-extension.ts`'s first line: the only signal that an installed file is ours. */
export const EXTENSION_MARKER = 'agile-agents — auto-generated by the daemon';

export class ForeignPiExtensionError extends Error {
  constructor(public readonly extensionPath: string) {
    super(
      `installPiExtension: refusing to overwrite ${extensionPath} — it does not contain the "${EXTENSION_MARKER}" marker, so it wasn't installed by this module. Remove or back it up before retrying.`,
    );
    this.name = 'ForeignPiExtensionError';
  }
}

export interface InstallPiExtensionOptions {
  /** `resolvePiAgentDir()`'s result, or a temp dir in tests. */
  agentDir: string;
  /** The extension's full source text, written unchanged. */
  extensionSource: string;
  /** `quietStartup: true` hides pi-acp's startup-info block (spike-findings.md §C4). Default true. */
  quietStartup?: boolean;
}

export interface InstallPiExtensionResult {
  extensionPath: string;
  settingsPath: string;
  /** False when the file already had identical content. */
  extensionWritten: boolean;
  /** False when `quietStartup` already matched, or the patch was skipped (`settingsError`). */
  settingsWritten: boolean;
  /** `settings.json` couldn't be parsed or patched and was left untouched. Never thrown. */
  settingsError?: string;
}

/**
 * Writes `<agentDir>/extensions/agile.ts` and patches `settings.json`.
 * Throws `ForeignPiExtensionError` rather than overwrite a file it didn't
 * install: the extension is the whole tier-1 gate, so that failure is
 * fatal. `settings.json` handling never throws.
 */
export function installPiExtension(opts: InstallPiExtensionOptions): InstallPiExtensionResult {
  const { agentDir, extensionSource } = opts;
  const quietStartup = opts.quietStartup ?? true;

  const extensionsDir = join(agentDir, 'extensions');
  mkdirSync(extensionsDir, { recursive: true });
  const extensionPath = join(extensionsDir, 'agile.ts');

  let extensionWritten = true;
  if (existsSync(extensionPath)) {
    const current = readFileSync(extensionPath, 'utf8');
    if (current === extensionSource) {
      extensionWritten = false;
    } else if (!current.includes(EXTENSION_MARKER)) {
      throw new ForeignPiExtensionError(extensionPath);
    }
  }
  if (extensionWritten) {
    writeFileSync(extensionPath, extensionSource);
  }

  const settingsPath = join(agentDir, 'settings.json');
  let settingsWritten = false;
  let settingsError: string | undefined;
  try {
    mkdirSync(agentDir, { recursive: true });
    let existing: Record<string, unknown> = {};
    if (existsSync(settingsPath)) {
      const parsed: unknown = JSON.parse(readFileSync(settingsPath, 'utf8'));
      if (isPlainObject(parsed)) existing = parsed;
    }
    settingsWritten = existing.quietStartup !== quietStartup;
    if (settingsWritten) {
      const merged = { ...existing, quietStartup };
      writeFileSync(settingsPath, `${JSON.stringify(merged, null, 2)}\n`);
    }
  } catch (err) {
    // Leave the file as found; never fail the install or the spawn.
    settingsWritten = false;
    settingsError = `left ${settingsPath} untouched (unparseable or unwritable): ${
      err instanceof Error ? err.message : String(err)
    }`;
  }

  return {
    extensionPath,
    settingsPath,
    extensionWritten,
    settingsWritten,
    ...(settingsError ? { settingsError } : {}),
  };
}
