/**
 * Installs the `agile` Pi extension (`agile-extension.ts`) into a Pi agent
 * directory's `extensions/` folder, and patches its `settings.json` for
 * `quietStartup` (T022 scope: "an `agile` Pi extension installed to
 * `~/.pi/agent/extensions/` ... `quietStartup` handling").
 *
 * The install step is a daemon/CLI action, not something baked into the
 * copied extension file itself — same split as Claude's
 * `hook/settings.ts`'s `writeClaudeSettings` (config generation) versus
 * `runner/session.ts` (the caller that actually invokes it per spawn).
 * `resolvePiAgentDir` mirrors `@earendil-works/pi-coding-agent`'s own
 * `getAgentDir()` (verified during T022's verify-before-build against
 * `dist/config.js`: `process.env.PI_CODING_AGENT_DIR ?? join(homedir(),
 * '.pi', 'agent')` — not re-implemented from that package, since depending
 * on it here would add a real dependency just to read one env var
 * convention) — passing `agentDir` explicitly (what every test does, via a
 * temp dir) always wins over both, so nothing here ever touches the real
 * home directory at test time.
 *
 * Idempotent by content: `installPiExtension` skips the write when the
 * target file's bytes already match (no spurious mtime bump / no risk of
 * clobbering a hand-edited copy that happens to already be identical), and
 * the `settings.json` patch only rewrites when `quietStartup` isn't already
 * set as requested — merging every other key untouched, same contract as
 * `writeClaudeSettings`.
 *
 * Round 2 review fixes (B2/B3):
 *
 * - **Foreign-file protection (B2)**: mirrors `merge/precommit.ts`'s
 *   `ForeignPreCommitHookError` pattern exactly — an existing
 *   `extensions/agile.ts` that doesn't carry `EXTENSION_MARKER` (this
 *   module's own copy always does, since it's `agile-extension.ts`'s own
 *   first line) wasn't installed by this module, so `installPiExtension`
 *   refuses to touch it rather than silently clobbering a Pi user's or
 *   Terma's own extension at the same well-known path (both use
 *   `~/.pi/agent/extensions/` — Terma's own `pi-integration.ts` marks its
 *   copy the same way, "auto-generated ... Do not edit", for the identical
 *   reason).
 * - **Defensive settings.json parsing (B3)**: a hand-written
 *   `~/.pi/agent/settings.json` is realistically JSONC (comments, trailing
 *   commas) — a hard `JSON.parse` used to throw straight out of
 *   `startAgentSession`, taking the whole Pi spawn down before the ACP
 *   process even existed. The settings patch is now entirely
 *   self-contained: an unparseable (or otherwise unwritable)
 *   `settings.json` is left byte-for-byte untouched and reported via
 *   `settingsError` rather than thrown — `quietStartup` is a noise-reduction
 *   nicety (spike-findings.md §C4), never worth blocking enforcement (the
 *   extension file write above, which *is* load-bearing, is not wrapped
 *   here and still throws/propagates normally).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

/** `PI_CODING_AGENT_DIR` — the same env var `@earendil-works/pi-coding-agent` and `pi-acp` both honor (verified in `node_modules/pi-acp@0.0.33/dist/index.js`: `process.env.PI_CODING_AGENT_DIR ? resolve(...) : join(homedir(), ".pi", "agent")`). */
export const PI_AGENT_DIR_ENV_VAR = 'PI_CODING_AGENT_DIR';

export interface ResolvePiAgentDirOptions {
  env?: Record<string, string | undefined>;
  homeDir?: string;
}

/** Resolves the Pi agent config directory the same way `pi`/`pi-acp` do. Never called with a real `homedir()` in a test — tests always pass `agentDir` explicitly to `installPiExtension` instead. */
export function resolvePiAgentDir(opts: ResolvePiAgentDirOptions = {}): string {
  const env = opts.env ?? process.env;
  const envDir = env[PI_AGENT_DIR_ENV_VAR];
  if (envDir) return envDir;
  return join(opts.homeDir ?? homedir(), '.pi', 'agent');
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Present on `agile-extension.ts`'s own first line — the only signal
 * `installPiExtension` has for "this file is ours" vs. "a Pi user (or
 * Terma) put something else at the same well-known path" (review round 2,
 * B2 — mirrors `merge/precommit.ts`'s `HOOK_MARKER`).
 */
export const EXTENSION_MARKER = 'agile-agents — auto-generated by the daemon';

export class ForeignPiExtensionError extends Error {
  constructor(public readonly extensionPath: string) {
    super(
      `installPiExtension: refusing to overwrite ${extensionPath} — it does not contain the "${EXTENSION_MARKER}" marker, so it wasn't installed by this module. Remove or back it up before retrying.`,
    );
    this.name = 'ForeignPiExtensionError';
  }
}

export interface InstallPiExtensionOptions {
  /** Pi agent config directory (`resolvePiAgentDir()`'s result, or an injected temp dir in tests). */
  agentDir: string;
  /** The extension's full source text — `install.ts`'s caller reads `agile-extension.ts` itself (see this file's header) and passes its contents through unchanged. */
  extensionSource: string;
  /** Set `quietStartup: true` in `settings.json` (spike-findings.md §C4: "Noise: pi-acp injects a 'startup info' block ... set `quietStartup: true` ... for agent use"). Default true. */
  quietStartup?: boolean;
}

export interface InstallPiExtensionResult {
  extensionPath: string;
  settingsPath: string;
  /** False when the extension file already had identical content on disk (idempotent no-op write). */
  extensionWritten: boolean;
  /** False when `settings.json` already had `quietStartup` set as requested (or when the patch was skipped — see `settingsError`). */
  settingsWritten: boolean;
  /** Set when `settings.json` exists but couldn't be parsed/patched — the file was left untouched (B3). Never thrown: `quietStartup` is cosmetic, not load-bearing. */
  settingsError?: string;
}

/**
 * Writes `<agentDir>/extensions/agile.ts` and patches
 * `<agentDir>/settings.json`. Safe to call on every daemon startup / every
 * Pi session spawn — both writes are idempotent no-ops once the target
 * state already matches.
 *
 * Throws `ForeignPiExtensionError` (B2) rather than overwriting an
 * `extensions/agile.ts` already present that this module didn't itself
 * install — that write IS load-bearing (it's the whole tier-1 gate for a
 * Pi session), so it's the one failure mode here that's still fatal.
 * `settings.json` handling (B3) never throws — see `settingsError`.
 */
export function installPiExtension(opts: InstallPiExtensionOptions): InstallPiExtensionResult {
  const { agentDir, extensionSource } = opts;
  const quietStartup = opts.quietStartup ?? true;

  const extensionsDir = join(agentDir, 'extensions');
  mkdirSync(extensionsDir, { recursive: true });
  const extensionPath = join(extensionsDir, 'agile.ts');

  let extensionWritten = true;
  if (existsSync(extensionPath)) {
    const current = readFileSync(extensionPath, 'utf8');
    if (current === extensionSource) {
      extensionWritten = false;
    } else if (!current.includes(EXTENSION_MARKER)) {
      throw new ForeignPiExtensionError(extensionPath);
    }
  }
  if (extensionWritten) {
    writeFileSync(extensionPath, extensionSource);
  }

  const settingsPath = join(agentDir, 'settings.json');
  let settingsWritten = false;
  let settingsError: string | undefined;
  try {
    mkdirSync(agentDir, { recursive: true });
    let existing: Record<string, unknown> = {};
    if (existsSync(settingsPath)) {
      const parsed: unknown = JSON.parse(readFileSync(settingsPath, 'utf8'));
      if (isPlainObject(parsed)) existing = parsed;
    }
    settingsWritten = existing.quietStartup !== quietStartup;
    if (settingsWritten) {
      const merged = { ...existing, quietStartup };
      writeFileSync(settingsPath, `${JSON.stringify(merged, null, 2)}\n`);
    }
  } catch (err) {
    // B3: a hand-edited/JSONC settings.json (comments, trailing commas) —
    // or any other read/parse/write failure here — must never take the
    // extension install (above, already done) or the caller's spawn down
    // with it. Leave the file exactly as it was found.
    settingsWritten = false;
    settingsError = `left ${settingsPath} untouched (unparseable or unwritable): ${
      err instanceof Error ? err.message : String(err)
    }`;
  }

  return {
    extensionPath,
    settingsPath,
    extensionWritten,
    settingsWritten,
    ...(settingsError ? { settingsError } : {}),
  };
}
